const HIRAGANA = [
  {
    kana: "あ",
    romaji: "a",
    exampleKana: "あさ",
    exampleRomaji: "asa",
    meaning: "pagi",
  },
  {
    kana: "い",
    romaji: "i",
    exampleKana: "いぬ",
    exampleRomaji: "inu",
    meaning: "anjing",
  },
  {
    kana: "う",
    romaji: "u",
    exampleKana: "うみ",
    exampleRomaji: "umi",
    meaning: "laut",
  },
  {
    kana: "え",
    romaji: "e",
    exampleKana: "えき",
    exampleRomaji: "eki",
    meaning: "stasiun",
  },
  {
    kana: "お",
    romaji: "o",
    exampleKana: "おとこ",
    exampleRomaji: "otoko",
    meaning: "pria",
  },
  {
    kana: "か",
    romaji: "ka",
    exampleKana: "かお",
    exampleRomaji: "kao",
    meaning: "wajah",
  },
  {
    kana: "き",
    romaji: "ki",
    exampleKana: "きのう",
    exampleRomaji: "kinou",
    meaning: "kemarin",
  },
  {
    kana: "く",
    romaji: "ku",
    exampleKana: "くつ",
    exampleRomaji: "kutsu",
    meaning: "sepatu",
  },
  {
    kana: "け",
    romaji: "ke",
    exampleKana: "けさ",
    exampleRomaji: "kesa",
    meaning: "tadi pagi",
  },
  {
    kana: "こ",
    romaji: "ko",
    exampleKana: "ここ",
    exampleRomaji: "koko",
    meaning: "sini",
  },
  {
    kana: "さ",
    romaji: "sa",
    exampleKana: "さかな",
    exampleRomaji: "sakana",
    meaning: "ikan",
  },
  {
    kana: "し",
    romaji: "shi",
    exampleKana: "しお",
    exampleRomaji: "shio",
    meaning: "garam",
  },
  {
    kana: "す",
    romaji: "su",
    exampleKana: "すし",
    exampleRomaji: "sushi",
    meaning: "sushi",
  },
  {
    kana: "せ",
    romaji: "se",
    exampleKana: "せかい",
    exampleRomaji: "sekai",
    meaning: "dunia",
  },
  {
    kana: "そ",
    romaji: "so",
    exampleKana: "そら",
    exampleRomaji: "sora",
    meaning: "langit",
  },
  {
    kana: "た",
    romaji: "ta",
    exampleKana: "たべる",
    exampleRomaji: "taberu",
    meaning: "makan",
  },
  {
    kana: "ち",
    romaji: "chi",
    exampleKana: "ちず",
    exampleRomaji: "chizu",
    meaning: "peta",
  },
  {
    kana: "つ",
    romaji: "tsu",
    exampleKana: "つき",
    exampleRomaji: "tsuki",
    meaning: "bulan",
  },
  {
    kana: "て",
    romaji: "te",
    exampleKana: "てがみ",
    exampleRomaji: "tegami",
    meaning: "surat",
  },
  {
    kana: "と",
    romaji: "to",
    exampleKana: "とけい",
    exampleRomaji: "tokei",
    meaning: "jam",
  },
  {
    kana: "な",
    romaji: "na",
    exampleKana: "なまえ",
    exampleRomaji: "namae",
    meaning: "nama",
  },
  {
    kana: "に",
    romaji: "ni",
    exampleKana: "にほん",
    exampleRomaji: "nihon",
    meaning: "Jepang",
  },
  {
    kana: "ぬ",
    romaji: "nu",
    exampleKana: "ぬの",
    exampleRomaji: "nuno",
    meaning: "kain",
  },
  {
    kana: "ね",
    romaji: "ne",
    exampleKana: "ねこ",
    exampleRomaji: "neko",
    meaning: "kucing",
  },
  {
    kana: "の",
    romaji: "no",
    exampleKana: "のむ",
    exampleRomaji: "nomu",
    meaning: "minum",
  },
  {
    kana: "は",
    romaji: "ha",
    exampleKana: "はな",
    exampleRomaji: "hana",
    meaning: "bunga",
  },
  {
    kana: "ひ",
    romaji: "hi",
    exampleKana: "ひと",
    exampleRomaji: "hito",
    meaning: "orang",
  },
  {
    kana: "ふ",
    romaji: "fu",
    exampleKana: "ふゆ",
    exampleRomaji: "fuyu",
    meaning: "musim dingin",
  },
  {
    kana: "へ",
    romaji: "he",
    exampleKana: "へや",
    exampleRomaji: "heya",
    meaning: "kamar",
  },
  {
    kana: "ほ",
    romaji: "ho",
    exampleKana: "ほん",
    exampleRomaji: "hon",
    meaning: "buku",
  },
  {
    kana: "ま",
    romaji: "ma",
    exampleKana: "まち",
    exampleRomaji: "machi",
    meaning: "kota",
  },
  {
    kana: "み",
    romaji: "mi",
    exampleKana: "みず",
    exampleRomaji: "mizu",
    meaning: "air",
  },
  {
    kana: "む",
    romaji: "mu",
    exampleKana: "むし",
    exampleRomaji: "mushi",
    meaning: "serangga",
  },
  {
    kana: "め",
    romaji: "me",
    exampleKana: "めがね",
    exampleRomaji: "megane",
    meaning: "kacamata",
  },
  {
    kana: "も",
    romaji: "mo",
    exampleKana: "もの",
    exampleRomaji: "mono",
    meaning: "barang",
  },
  {
    kana: "や",
    romaji: "ya",
    exampleKana: "やま",
    exampleRomaji: "yama",
    meaning: "gunung",
  },
  {
    kana: "ゆ",
    romaji: "yu",
    exampleKana: "ゆき",
    exampleRomaji: "yuki",
    meaning: "salju",
  },
  {
    kana: "よ",
    romaji: "yo",
    exampleKana: "よる",
    exampleRomaji: "yoru",
    meaning: "malam",
  },
  {
    kana: "ら",
    romaji: "ra",
    exampleKana: "らいねん",
    exampleRomaji: "rainen",
    meaning: "tahun depan",
  },
  {
    kana: "り",
    romaji: "ri",
    exampleKana: "りんご",
    exampleRomaji: "ringo",
    meaning: "apel",
  },
  {
    kana: "る",
    romaji: "ru",
    exampleKana: "るす",
    exampleRomaji: "rusu",
    meaning: "tidak di rumah",
  },
  {
    kana: "れ",
    romaji: "re",
    exampleKana: "れきし",
    exampleRomaji: "rekishi",
    meaning: "sejarah",
  },
  {
    kana: "ろ",
    romaji: "ro",
    exampleKana: "ろく",
    exampleRomaji: "roku",
    meaning: "enam",
  },
  {
    kana: "わ",
    romaji: "wa",
    exampleKana: "わたし",
    exampleRomaji: "watashi",
    meaning: "saya",
  },
  {
    kana: "を",
    romaji: "wo",
    exampleKana: "ほんを",
    exampleRomaji: "hon wo",
    meaning: "buku (objek)",
  },
  {
    kana: "ん",
    romaji: "n",
    exampleKana: "にほん",
    exampleRomaji: "nihon",
    meaning: "Jepang",
  },
];
export default HIRAGANA;
