const KANJI_N5 = [
  {
    kanji: "日",
    onyomi: "ニチ / ジツ",
    kunyomi: "ひ / -び / -か",
    example: "日本 (にほん)",
    exampleRomaji: "nihon",
    meaning: "Jepang; hari; matahari",
    jlpt: "N5",
  },
  {
    kanji: "一",
    onyomi: "イチ / イツ",
    kunyomi: "ひと- / ひと.つ",
    example: "一つ (ひとつ)",
    exampleRomaji: "hitotsu",
    meaning: "satu",
    jlpt: "N5",
  },
  {
    kanji: "二",
    onyomi: "ニ",
    kunyomi: "ふた- / ふたつ",
    example: "二人 (ふたり)",
    exampleRomaji: "futari",
    meaning: "dua / dua orang",
    jlpt: "N5",
  },
  {
    kanji: "三",
    onyomi: "サン",
    kunyomi: "み- / みっつ",
    example: "三月 (さんがつ)",
    exampleRomaji: "sangatsu",
    meaning: "tiga / bulan Maret",
    jlpt: "N5",
  },
  {
    kanji: "四",
    onyomi: "シ",
    kunyomi: "よん / よ / よっつ",
    example: "四つ (よっつ)",
    exampleRomaji: "yottsu",
    meaning: "empat",
    jlpt: "N5",
  },
  {
    kanji: "五",
    onyomi: "ゴ",
    kunyomi: "いつ / いつつ",
    example: "五分 (ごふん)",
    exampleRomaji: "gofun",
    meaning: "lima / menit",
    jlpt: "N5",
  },
  {
    kanji: "六",
    onyomi: "ロク",
    kunyomi: "む / むっつ / むい",
    example: "六時 (ろくじ)",
    exampleRomaji: "rokuji",
    meaning: "enam / jam",
    jlpt: "N5",
  },
  {
    kanji: "七",
    onyomi: "シチ",
    kunyomi: "なな / ななつ / なの",
    example: "七日 (なのか)",
    exampleRomaji: "nanoka",
    meaning: "tujuh / tanggal 7",
    jlpt: "N5",
  },
  {
    kanji: "八",
    onyomi: "ハチ",
    kunyomi: "や / やっつ / よう",
    example: "八月 (はちがつ)",
    exampleRomaji: "hachigatsu",
    meaning: "delapan / Agustus",
    jlpt: "N5",
  },
  {
    kanji: "九",
    onyomi: "キュウ / ク",
    kunyomi: "ここの / ここのつ",
    example: "九時 (くじ)",
    exampleRomaji: "kuji",
    meaning: "sembilan",
    jlpt: "N5",
  },
  {
    kanji: "十",
    onyomi: "ジュウ / ジッ",
    kunyomi: "とお / と",
    example: "十分 (じゅっぷん)",
    exampleRomaji: "juppun",
    meaning: "sepuluh; cukup; menit",
    jlpt: "N5",
  },
  {
    kanji: "百",
    onyomi: "ヒャク",
    kunyomi: "",
    example: "百円 (ひゃくえん)",
    exampleRomaji: "hyaku en",
    meaning: "seratus",
    jlpt: "N5",
  },
  {
    kanji: "千",
    onyomi: "セン",
    kunyomi: "ち",
    example: "千円 (せんえん)",
    exampleRomaji: "sen en",
    meaning: "seribu",
    jlpt: "N5",
  },
  {
    kanji: "万",
    onyomi: "マン / バン",
    kunyomi: "",
    example: "一万円 (いちまんえん)",
    exampleRomaji: "ichiman en",
    meaning: "sepuluh ribu",
    jlpt: "N5",
  },
  {
    kanji: "年",
    onyomi: "ネン",
    kunyomi: "とし",
    example: "今年 (ことし)",
    exampleRomaji: "kotoshi",
    meaning: "tahun",
    jlpt: "N5",
  },
  {
    kanji: "月",
    onyomi: "ゲツ / ガツ",
    kunyomi: "つき",
    example: "月曜日 (げつようび)",
    exampleRomaji: "getsuyoubi",
    meaning: "bulan; hari Senin",
    jlpt: "N5",
  },
  {
    kanji: "火",
    onyomi: "カ",
    kunyomi: "ひ / -び",
    example: "火曜日 (かようび)",
    exampleRomaji: "kayoubi",
    meaning: "api; hari Selasa",
    jlpt: "N5",
  },
  {
    kanji: "水",
    onyomi: "スイ",
    kunyomi: "みず",
    example: "水 (みず)",
    exampleRomaji: "mizu",
    meaning: "air; hari Rabu",
    jlpt: "N5",
  },
  {
    kanji: "木",
    onyomi: "モク / ボク",
    kunyomi: "き / こ-",
    example: "木曜日 (もくようび)",
    exampleRomaji: "mokuyoubi",
    meaning: "pohon; hari Kamis",
    jlpt: "N5",
  },
  {
    kanji: "金",
    onyomi: "キン / コン",
    kunyomi: "かね / -がね",
    example: "お金 (おかね)",
    exampleRomaji: "okane",
    meaning: "emas; uang; hari Jumat",
    jlpt: "N5",
  },
  {
    kanji: "土",
    onyomi: "ド / ト",
    kunyomi: "つち",
    example: "土曜日 (どようび)",
    exampleRomaji: "doyoubi",
    meaning: "tanah; hari Sabtu",
    jlpt: "N5",
  },
  {
    kanji: "曜",
    onyomi: "ヨウ",
    kunyomi: "",
    example: "日曜日 (にちようび)",
    exampleRomaji: "nichiyoubi",
    meaning: "hari minggu (akhiran hari)",
    jlpt: "N5",
  },
  {
    kanji: "今",
    onyomi: "コン / キン",
    kunyomi: "いま",
    example: "今 (いま)",
    exampleRomaji: "ima",
    meaning: "sekarang",
    jlpt: "N5",
  },
  {
    kanji: "明",
    onyomi: "メイ / ミョウ",
    kunyomi: "あ- / あか- / あき-",
    example: "明日 (あした / あす)",
    exampleRomaji: "ashita / asu",
    meaning: "terang; besok",
    jlpt: "N5",
  },
  {
    kanji: "朝",
    onyomi: "チョウ",
    kunyomi: "あさ",
    example: "今朝 (けさ)",
    exampleRomaji: "kesa",
    meaning: "pagi",
    jlpt: "N5",
  },
  {
    kanji: "昼",
    onyomi: "チュウ",
    kunyomi: "ひる",
    example: "昼ごはん (ひるごはん)",
    exampleRomaji: "hiru gohan",
    meaning: "siang; makan siang",
    jlpt: "N5",
  },
  {
    kanji: "夜",
    onyomi: "ヤ",
    kunyomi: "よる / よ",
    example: "今夜 (こんや)",
    exampleRomaji: "konya",
    meaning: "malam",
    jlpt: "N5",
  },
  {
    kanji: "半",
    onyomi: "ハン",
    kunyomi: "なか- / なかば",
    example: "半分 (はんぶん)",
    exampleRomaji: "hanbun",
    meaning: "setengah",
    jlpt: "N5",
  },
  {
    kanji: "時",
    onyomi: "ジ",
    kunyomi: "とき",
    example: "一時 (いちじ)",
    exampleRomaji: "ichiji",
    meaning: "waktu; jam",
    jlpt: "N5",
  },
  {
    kanji: "間",
    onyomi: "カン / ケン",
    kunyomi: "あいだ / ま",
    example: "時間 (じかん)",
    exampleRomaji: "jikan",
    meaning: "jarak/waktu; durasi",
    jlpt: "N5",
  },
  {
    kanji: "先",
    onyomi: "セン",
    kunyomi: "さき / ま.ず",
    example: "先生 (せんせい)",
    exampleRomaji: "sensei",
    meaning: "sebelum; guru",
    jlpt: "N5",
  },
  {
    kanji: "生",
    onyomi: "セイ / ショウ",
    kunyomi: "い- / う- / お- / は- / なま",
    example: "学生 (がくせい)",
    exampleRomaji: "gakusei",
    meaning: "hidup; lahir; siswa",
    jlpt: "N5",
  },
  {
    kanji: "学",
    onyomi: "ガク",
    kunyomi: "まな-ぶ",
    example: "学校 (がっこう)",
    exampleRomaji: "gakkou",
    meaning: "belajar; sekolah",
    jlpt: "N5",
  },
  {
    kanji: "校",
    onyomi: "コウ",
    kunyomi: "",
    example: "学校 (がっこう)",
    exampleRomaji: "gakkou",
    meaning: "sekolah (khusus)",
    jlpt: "N5",
  },
  {
    kanji: "先",
    onyomi: "セン",
    kunyomi: "さき",
    example: "先生 (せんせい)",
    exampleRomaji: "sensei",
    meaning: "guru; senior",
    jlpt: "N5",
  },
  {
    kanji: "分",
    onyomi: "ブン / フン / ブ",
    kunyomi: "わ-かる / わ-ける",
    example: "十分 (じゅっぷん)",
    exampleRomaji: "juppun",
    meaning: "bagian; menit; membagi",
    jlpt: "N5",
  },
  {
    kanji: "入",
    onyomi: "ニュウ",
    kunyomi: "い-る / はい-る / い-れる",
    example: "入る (はいる)",
    exampleRomaji: "hairu",
    meaning: "masuk",
    jlpt: "N5",
  },
  {
    kanji: "出",
    onyomi: "シュツ / スイ",
    kunyomi: "で-る / だ-す",
    example: "出る (でる)",
    exampleRomaji: "deru",
    meaning: "keluar",
    jlpt: "N5",
  },
  {
    kanji: "立",
    onyomi: "リツ / リュウ",
    kunyomi: "た-つ / た-てる",
    example: "立つ (たつ)",
    exampleRomaji: "tatsu",
    meaning: "berdiri",
    jlpt: "N5",
  },
  {
    kanji: "休",
    onyomi: "キュウ",
    kunyomi: "やす-む / やす-まる / やす-める",
    example: "休み (やすみ)",
    exampleRomaji: "yasumi",
    meaning: "istirahat; libur",
    jlpt: "N5",
  },
  {
    kanji: "先",
    onyomi: "セン",
    kunyomi: "さき",
    example: "先生 (せんせい)",
    exampleRomaji: "sensei",
    meaning: "guru / sebelumnya",
    jlpt: "N5",
  },
  {
    kanji: "何",
    onyomi: "カ / ナニ",
    kunyomi: "なに / なん",
    example: "何 (なに)",
    exampleRomaji: "nani",
    meaning: "apa",
    jlpt: "N5",
  },
  {
    kanji: "誰",
    onyomi: "スイ",
    kunyomi: "だれ / たれ",
    example: "誰 (だれ)",
    exampleRomaji: "dare",
    meaning: "siapa",
    jlpt: "N5",
  },
  {
    kanji: "何時",
    onyomi: "",
    kunyomi: "",
    example: "何時 (いつ / なんじ)",
    exampleRomaji: "itsu / nanji",
    meaning: "kapan / jam berapa",
    jlpt: "N5",
  },
  {
    kanji: "人",
    onyomi: "ジン / ニン",
    kunyomi: "ひと",
    example: "人 (ひと)",
    exampleRomaji: "hito",
    meaning: "orang",
    jlpt: "N5",
  },
  {
    kanji: "友",
    onyomi: "ユウ",
    kunyomi: "とも",
    example: "友だち (ともだち)",
    exampleRomaji: "tomodachi",
    meaning: "teman",
    jlpt: "N5",
  },
  {
    kanji: "父",
    onyomi: "フ / フウ",
    kunyomi: "ちち",
    example: "父 (ちち)",
    exampleRomaji: "chichi",
    meaning: "ayah (ambiguous—bentuk saya)",
    jlpt: "N5",
  },
  {
    kanji: "母",
    onyomi: "ボ",
    kunyomi: "はは",
    example: "母 (はは)",
    exampleRomaji: "haha",
    meaning: "ibu (bentuk saya)",
    jlpt: "N5",
  },
  {
    kanji: "兄",
    onyomi: "ケイ / キョウ",
    kunyomi: "あに",
    example: "兄 (あに)",
    exampleRomaji: "ani",
    meaning: "kakak laki-laki (saya)",
    jlpt: "N5",
  },
  {
    kanji: "姉",
    onyomi: "シ",
    kunyomi: "あね",
    example: "姉 (あね)",
    exampleRomaji: "ane",
    meaning: "kakak perempuan (saya)",
    jlpt: "N5",
  },
  {
    kanji: "弟",
    onyomi: "テイ / ダイ",
    kunyomi: "おとうと",
    example: "弟 (おとうと)",
    exampleRomaji: "otouto",
    meaning: "adik laki-laki",
    jlpt: "N5",
  },
  {
    kanji: "妹",
    onyomi: "マイ",
    kunyomi: "いもうと",
    example: "妹 (いもうと)",
    exampleRomaji: "imouto",
    meaning: "adik perempuan",
    jlpt: "N5",
  },
  {
    kanji: "子",
    onyomi: "シ / ス / ツ",
    kunyomi: "こ / -こ / ね",
    example: "子ども (こども)",
    exampleRomaji: "kodomo",
    meaning: "anak",
    jlpt: "N5",
  },
  {
    kanji: "女",
    onyomi: "ジョ / ニョ / ニョウ",
    kunyomi: "おんな / め",
    example: "女の人 (おんなのひと)",
    exampleRomaji: "onnanohito",
    meaning: "perempuan",
    jlpt: "N5",
  },
  {
    kanji: "男",
    onyomi: "ダン / ナン",
    kunyomi: "おとこ",
    example: "男の人 (おとこのひと)",
    exampleRomaji: "otokonohito",
    meaning: "laki-laki",
    jlpt: "N5",
  },
  {
    kanji: "見",
    onyomi: "ケン",
    kunyomi: "み-る / み-える / み-せる",
    example: "見る (みる)",
    exampleRomaji: "miru",
    meaning: "melihat",
    jlpt: "N5",
  },
  {
    kanji: "行",
    onyomi: "コウ / ギョウ",
    kunyomi: "い-く / ゆ-く / おこな-う",
    example: "行く (いく)",
    exampleRomaji: "iku",
    meaning: "pergi",
    jlpt: "N5",
  },
  {
    kanji: "来",
    onyomi: "ライ",
    kunyomi: "く-る / き-ます / き-た",
    example: "来る (くる)",
    exampleRomaji: "kuru",
    meaning: "datang",
    jlpt: "N5",
  },
  {
    kanji: "帰",
    onyomi: "キ",
    kunyomi: "かえ-る / かえ-す",
    example: "帰る (かえる)",
    exampleRomaji: "kaeru",
    meaning: "pulang",
    jlpt: "N5",
  },
  {
    kanji: "買",
    onyomi: "バイ",
    kunyomi: "か-う",
    example: "買う (かう)",
    exampleRomaji: "kau",
    meaning: "membeli",
    jlpt: "N5",
  },
  {
    kanji: "売",
    onyomi: "バイ",
    kunyomi: "う-る / う-れる",
    example: "売る (うる)",
    exampleRomaji: "uru",
    meaning: "menjual",
    jlpt: "N5",
  },
  {
    kanji: "食",
    onyomi: "ショク / ジキ",
    kunyomi: "く-う / く-らう / た-べる",
    example: "食べる (たべる)",
    exampleRomaji: "taberu",
    meaning: "makan",
    jlpt: "N5",
  },
  {
    kanji: "飲",
    onyomi: "イン",
    kunyomi: "の-む",
    example: "飲む (のむ)",
    exampleRomaji: "nomu",
    meaning: "minum",
    jlpt: "N5",
  },
  {
    kanji: "見",
    onyomi: "ケン",
    kunyomi: "みる",
    example: "見せる (みせる)",
    exampleRomaji: "miseru",
    meaning: "menunjukkan",
    jlpt: "N5",
  },
  {
    kanji: "聞",
    onyomi: "ブン / モン",
    kunyomi: "き-く / き-こえる",
    example: "聞く (きく)",
    exampleRomaji: "kiku",
    meaning: "mendengar / bertanya",
    jlpt: "N5",
  },
  {
    kanji: "話",
    onyomi: "ワ",
    kunyomi: "はな-す / はなし",
    example: "話す (はなす)",
    exampleRomaji: "hanasu",
    meaning: "bicara; cerita",
    jlpt: "N5",
  },
  {
    kanji: "書",
    onyomi: "ショ",
    kunyomi: "か-く",
    example: "書く (かく)",
    exampleRomaji: "kaku",
    meaning: "menulis",
    jlpt: "N5",
  },
  {
    kanji: "読",
    onyomi: "ドク / トク / トウ",
    kunyomi: "よ-む",
    example: "読む (よむ)",
    exampleRomaji: "yomu",
    meaning: "membaca",
    jlpt: "N5",
  },
  {
    kanji: "聞",
    onyomi: "ブン / モン",
    kunyomi: "き-く",
    example: "新聞 (しんぶん)",
    exampleRomaji: "shinbun",
    meaning: "koran",
    jlpt: "N5",
  },
  {
    kanji: "車",
    onyomi: "シャ",
    kunyomi: "くるま",
    example: "車 (くるま)",
    exampleRomaji: "kuruma",
    meaning: "mobil",
    jlpt: "N5",
  },
  {
    kanji: "電",
    onyomi: "デン",
    kunyomi: "",
    example: "電車 (でんしゃ)",
    exampleRomaji: "densha",
    meaning: "listrik; kereta listrik",
    jlpt: "N5",
  },
  {
    kanji: "駅",
    onyomi: "エキ",
    kunyomi: "",
    example: "駅 (えき)",
    exampleRomaji: "eki",
    meaning: "stasiun",
    jlpt: "N5",
  },
  {
    kanji: "道",
    onyomi: "ドウ / トウ",
    kunyomi: "みち",
    example: "道 (みち)",
    exampleRomaji: "michi",
    meaning: "jalan; cara",
    jlpt: "N5",
  },
  {
    kanji: "海",
    onyomi: "カイ",
    kunyomi: "うみ",
    example: "海 (うみ)",
    exampleRomaji: "umi",
    meaning: "laut",
    jlpt: "N5",
  },
  {
    kanji: "山",
    onyomi: "サン / セン",
    kunyomi: "やま",
    example: "山 (やま)",
    exampleRomaji: "yama",
    meaning: "gunung",
    jlpt: "N5",
  },
  {
    kanji: "川",
    onyomi: "セン",
    kunyomi: "かわ",
    example: "川 (かわ)",
    exampleRomaji: "kawa",
    meaning: "sungai",
    jlpt: "N5",
  },
  {
    kanji: "空",
    onyomi: "クウ",
    kunyomi: "そら / あ-く / あ-ける",
    example: "空 (そら)",
    exampleRomaji: "sora",
    meaning: "langit; kosong",
    jlpt: "N5",
  },
  {
    kanji: "雨",
    onyomi: "ウ",
    kunyomi: "あめ / あま-",
    example: "雨 (あめ)",
    exampleRomaji: "ame",
    meaning: "hujan",
    jlpt: "N5",
  },
  {
    kanji: "雪",
    onyomi: "セツ",
    kunyomi: "ゆき",
    example: "雪 (ゆき)",
    exampleRomaji: "yuki",
    meaning: "salju",
    jlpt: "N5",
  },
  {
    kanji: "花",
    onyomi: "カ",
    kunyomi: "はな",
    example: "花 (はな)",
    exampleRomaji: "hana",
    meaning: "bunga",
    jlpt: "N5",
  },
  {
    kanji: "草",
    onyomi: "ソウ",
    kunyomi: "くさ",
    example: "草 (くさ)",
    exampleRomaji: "kusa",
    meaning: "rumput",
    jlpt: "N5",
  },
  {
    kanji: "犬",
    onyomi: "ケン",
    kunyomi: "いぬ",
    example: "犬 (いぬ)",
    exampleRomaji: "inu",
    meaning: "anjing",
    jlpt: "N5",
  },
  {
    kanji: "魚",
    onyomi: "ギョ",
    kunyomi: "さかな / -ざかな",
    example: "魚 (さかな)",
    exampleRomaji: "sakana",
    meaning: "ikan",
    jlpt: "N5",
  },
  {
    kanji: "鳥",
    onyomi: "チョウ",
    kunyomi: "とり",
    example: "鳥 (とり)",
    exampleRomaji: "tori",
    meaning: "burung",
    jlpt: "N5",
  },
  {
    kanji: "肉",
    onyomi: "ニク",
    kunyomi: "",
    example: "肉 (にく)",
    exampleRomaji: "niku",
    meaning: "daging",
    jlpt: "N5",
  },
  {
    kanji: "店",
    onyomi: "テン",
    kunyomi: "みせ",
    example: "店 (みせ)",
    exampleRomaji: "mise",
    meaning: "toko",
    jlpt: "N5",
  },
  {
    kanji: "安",
    onyomi: "アン",
    kunyomi: "やす-い",
    example: "安い (やすい)",
    exampleRomaji: "yasui",
    meaning: "murah; tenang",
    jlpt: "N5",
  },
  {
    kanji: "高",
    onyomi: "コウ",
    kunyomi: "たか-い / たか",
    example: "高い (たかい)",
    exampleRomaji: "takai",
    meaning: "tinggi; mahal",
    jlpt: "N5",
  },
  {
    kanji: "新",
    onyomi: "シン",
    kunyomi: "あたら-しい / あら-た",
    example: "新しい (あたらしい)",
    exampleRomaji: "atarashii",
    meaning: "baru",
    jlpt: "N5",
  },
  {
    kanji: "古",
    onyomi: "コ",
    kunyomi: "ふる-い",
    example: "古い (ふるい)",
    exampleRomaji: "furui",
    meaning: "lama; tua",
    jlpt: "N5",
  },
  {
    kanji: "短",
    onyomi: "タン",
    kunyomi: "みじか-い",
    example: "短い (みじかい)",
    exampleRomaji: "mijikai",
    meaning: "pendek",
    jlpt: "N5",
  },
  {
    kanji: "長",
    onyomi: "チョウ",
    kunyomi: "なが-い",
    example: "長い (ながい)",
    exampleRomaji: "nagai",
    meaning: "panjang; lama",
    jlpt: "N5",
  },
  {
    kanji: "白",
    onyomi: "ハク / ビャク",
    kunyomi: "しろ / しら-",
    example: "白い (しろい)",
    exampleRomaji: "shiroi",
    meaning: "putih",
    jlpt: "N5",
  },
  {
    kanji: "黒",
    onyomi: "コク",
    kunyomi: "くろ / くろ-い",
    example: "黒い (くろい)",
    exampleRomaji: "kuroi",
    meaning: "hitam",
    jlpt: "N5",
  },
  {
    kanji: "赤",
    onyomi: "セキ / シャク",
    kunyomi: "あか / あか-い",
    example: "赤い (あかい)",
    exampleRomaji: "akai",
    meaning: "merah",
    jlpt: "N5",
  },
  {
    kanji: "青",
    onyomi: "セイ / ショウ",
    kunyomi: "あお / あお-い",
    example: "青い (あおい)",
    exampleRomaji: "aoi",
    meaning: "biru / hijau muda (konteks)",
    jlpt: "N5",
  },
  {
    kanji: "円",
    onyomi: "エン",
    kunyomi: "まる-い",
    example: "円 (えん)",
    exampleRomaji: "en",
    meaning: "yen; lingkaran",
    jlpt: "N5",
  },
  {
    kanji: "名",
    onyomi: "メイ / ミョウ",
    kunyomi: "な",
    example: "名前 (なまえ)",
    exampleRomaji: "namae",
    meaning: "nama",
    jlpt: "N5",
  },
  {
    kanji: "口",
    onyomi: "コウ / ク",
    kunyomi: "くち",
    example: "出口 (でぐち)",
    exampleRomaji: "deguchi",
    meaning: "mulut; pintu keluar",
    jlpt: "N5",
  },
  {
    kanji: "目",
    onyomi: "モク / ボク",
    kunyomi: "め / -め / ま-",
    example: "目 (め)",
    exampleRomaji: "me",
    meaning: "mata; tujuan",
    jlpt: "N5",
  },
  {
    kanji: "耳",
    onyomi: "ジ / ニ",
    kunyomi: "みみ",
    example: "耳 (みみ)",
    exampleRomaji: "mimi",
    meaning: "telinga",
    jlpt: "N5",
  },
  {
    kanji: "手",
    onyomi: "シュ / ズ",
    kunyomi: "て / て- / -て",
    example: "手 (て)",
    exampleRomaji: "te",
    meaning: "tangan",
    jlpt: "N5",
  },
  {
    kanji: "足",
    onyomi: "ソク",
    kunyomi: "あし / た-りる / た-る",
    example: "足 (あし)",
    exampleRomaji: "ashi",
    meaning: "kaki; cukup",
    jlpt: "N5",
  },
  {
    kanji: "力",
    onyomi: "リョク / リキ",
    kunyomi: "ちから",
    example: "力 (ちから)",
    exampleRomaji: "chikara",
    meaning: "kekuatan",
    jlpt: "N5",
  },
  {
    kanji: "気",
    onyomi: "キ / ケ",
    kunyomi: "いき",
    example: "元気 (げんき)",
    exampleRomaji: "genki",
    meaning: "energi; semangat",
    jlpt: "N5",
  },
  {
    kanji: "病",
    onyomi: "ビョウ / ヘイ",
    kunyomi: "や-む / やまい",
    example: "病気 (びょうき)",
    exampleRomaji: "byouki",
    meaning: "sakit; penyakit",
    jlpt: "N5",
  },
  {
    kanji: "医",
    onyomi: "イ",
    kunyomi: "",
    example: "医者 (いしゃ)",
    exampleRomaji: "isha",
    meaning: "dokter",
    jlpt: "N5",
  },
  {
    kanji: "家",
    onyomi: "カ / ケ",
    kunyomi: "いえ / や",
    example: "家 (いえ)",
    exampleRomaji: "ie",
    meaning: "rumah; keluarga",
    jlpt: "N5",
  },
  {
    kanji: "道",
    onyomi: "ドウ",
    kunyomi: "みち",
    example: "道 (みち)",
    exampleRomaji: "michi",
    meaning: "jalan; cara",
    jlpt: "N5",
  },
  {
    kanji: "会",
    onyomi: "カイ / エ",
    kunyomi: "あ-う",
    example: "会社 (かいしゃ)",
    exampleRomaji: "kaisha",
    meaning: "pertemuan; perusahaan",
    jlpt: "N5",
  },
  {
    kanji: "社",
    onyomi: "シャ",
    kunyomi: "やしろ",
    example: "会社 (かいしゃ)",
    exampleRomaji: "kaisha",
    meaning: "perusahaan; kuil kecil",
    jlpt: "N5",
  },
  {
    kanji: "同",
    onyomi: "ドウ",
    kunyomi: "おな-じ",
    example: "同じ (おなじ)",
    exampleRomaji: "onaji",
    meaning: "sama",
    jlpt: "N5",
  },
  {
    kanji: "時間",
    onyomi: "",
    kunyomi: "",
    example: "時間 (じかん)",
    exampleRomaji: "jikan",
    meaning: "waktu (durasi)",
    jlpt: "N5",
  },
];

export default KANJI_N5;
