const KATAKANA = [
  {
    kana: "ア",
    romaji: "a",
    exampleKana: "アメリカ",
    exampleRomaji: "amerika",
    meaning: "Amerika",
  },
  {
    kana: "イ",
    romaji: "i",
    exampleKana: "イタリア",
    exampleRomaji: "itaria",
    meaning: "Italia",
  },
  {
    kana: "ウ",
    romaji: "u",
    exampleKana: "ウイスキー",
    exampleRomaji: "uisukii",
    meaning: "wiski",
  },
  {
    kana: "エ",
    romaji: "e",
    exampleKana: "エアコン",
    exampleRomaji: "eakon",
    meaning: "AC",
  },
  {
    kana: "オ",
    romaji: "o",
    exampleKana: "オレンジ",
    exampleRomaji: "orenji",
    meaning: "jeruk",
  },
  {
    kana: "カ",
    romaji: "ka",
    exampleKana: "カメラ",
    exampleRomaji: "kamera",
    meaning: "kamera",
  },
  {
    kana: "キ",
    romaji: "ki",
    exampleKana: "キロ",
    exampleRomaji: "kiro",
    meaning: "kilo",
  },
  {
    kana: "ク",
    romaji: "ku",
    exampleKana: "クラス",
    exampleRomaji: "kurasu",
    meaning: "kelas",
  },
  {
    kana: "ケ",
    romaji: "ke",
    exampleKana: "ケーキ",
    exampleRomaji: "keeki",
    meaning: "kue",
  },
  {
    kana: "コ",
    romaji: "ko",
    exampleKana: "コーヒー",
    exampleRomaji: "koohii",
    meaning: "kopi",
  },
  {
    kana: "サ",
    romaji: "sa",
    exampleKana: "サラダ",
    exampleRomaji: "sarada",
    meaning: "salad",
  },
  {
    kana: "シ",
    romaji: "shi",
    exampleKana: "シャツ",
    exampleRomaji: "shatsu",
    meaning: "kemeja",
  },
  {
    kana: "ス",
    romaji: "su",
    exampleKana: "スーパー",
    exampleRomaji: "suupaa",
    meaning: "supermarket",
  },
  {
    kana: "セ",
    romaji: "se",
    exampleKana: "セーター",
    exampleRomaji: "seetaa",
    meaning: "sweater",
  },
  {
    kana: "ソ",
    romaji: "so",
    exampleKana: "ソース",
    exampleRomaji: "soosu",
    meaning: "saus",
  },
  {
    kana: "タ",
    romaji: "ta",
    exampleKana: "タクシー",
    exampleRomaji: "takushii",
    meaning: "taksi",
  },
  {
    kana: "チ",
    romaji: "chi",
    exampleKana: "チーズ",
    exampleRomaji: "chiizu",
    meaning: "keju",
  },
  {
    kana: "ツ",
    romaji: "tsu",
    exampleKana: "ツアー",
    exampleRomaji: "tsuaa",
    meaning: "tur",
  },
  {
    kana: "テ",
    romaji: "te",
    exampleKana: "テレビ",
    exampleRomaji: "terebi",
    meaning: "TV",
  },
  {
    kana: "ト",
    romaji: "to",
    exampleKana: "トイレ",
    exampleRomaji: "toire",
    meaning: "toilet",
  },
  {
    kana: "ナ",
    romaji: "na",
    exampleKana: "ナイフ",
    exampleRomaji: "naifu",
    meaning: "pisau",
  },
  {
    kana: "ニ",
    romaji: "ni",
    exampleKana: "ニュース",
    exampleRomaji: "nyuusu",
    meaning: "berita",
  },
  {
    kana: "ヌ",
    romaji: "nu",
    exampleKana: "ヌードル",
    exampleRomaji: "nuudoru",
    meaning: "mie",
  },
  {
    kana: "ネ",
    romaji: "ne",
    exampleKana: "ネクタイ",
    exampleRomaji: "nekutai",
    meaning: "dasi",
  },
  {
    kana: "ノ",
    romaji: "no",
    exampleKana: "ノート",
    exampleRomaji: "nooto",
    meaning: "buku catatan",
  },
  {
    kana: "ハ",
    romaji: "ha",
    exampleKana: "ハンバーガー",
    exampleRomaji: "hanbagaa",
    meaning: "hamburger",
  },
  {
    kana: "ヒ",
    romaji: "hi",
    exampleKana: "ヒーター",
    exampleRomaji: "hiitaa",
    meaning: "pemanas",
  },
  {
    kana: "フ",
    romaji: "fu",
    exampleKana: "フォーク",
    exampleRomaji: "fooku",
    meaning: "garpu",
  },
  {
    kana: "ヘ",
    romaji: "he",
    exampleKana: "ヘリコプター",
    exampleRomaji: "herikoputaa",
    meaning: "helikopter",
  },
  {
    kana: "ホ",
    romaji: "ho",
    exampleKana: "ホテル",
    exampleRomaji: "hoteru",
    meaning: "hotel",
  },
  {
    kana: "マ",
    romaji: "ma",
    exampleKana: "マンガ",
    exampleRomaji: "manga",
    meaning: "manga",
  },
  {
    kana: "ミ",
    romaji: "mi",
    exampleKana: "ミルク",
    exampleRomaji: "miruku",
    meaning: "susu",
  },
  {
    kana: "ム",
    romaji: "mu",
    exampleKana: "ムービー",
    exampleRomaji: "muubii",
    meaning: "film",
  },
  {
    kana: "メ",
    romaji: "me",
    exampleKana: "メニュー",
    exampleRomaji: "menyuu",
    meaning: "menu",
  },
  {
    kana: "モ",
    romaji: "mo",
    exampleKana: "モデル",
    exampleRomaji: "moderu",
    meaning: "model",
  },
  {
    kana: "ヤ",
    romaji: "ya",
    exampleKana: "ヤング",
    exampleRomaji: "yangu",
    meaning: "muda",
  },
  {
    kana: "ユ",
    romaji: "yu",
    exampleKana: "ユーザー",
    exampleRomaji: "yuuzaa",
    meaning: "pengguna",
  },
  {
    kana: "ヨ",
    romaji: "yo",
    exampleKana: "ヨーグルト",
    exampleRomaji: "yooguruto",
    meaning: "yogurt",
  },
  {
    kana: "ラ",
    romaji: "ra",
    exampleKana: "ラジオ",
    exampleRomaji: "rajio",
    meaning: "radio",
  },
  {
    kana: "リ",
    romaji: "ri",
    exampleKana: "リボン",
    exampleRomaji: "ribon",
    meaning: "pita",
  },
  {
    kana: "ル",
    romaji: "ru",
    exampleKana: "ルール",
    exampleRomaji: "ruuru",
    meaning: "aturan",
  },
  {
    kana: "レ",
    romaji: "re",
    exampleKana: "レストラン",
    exampleRomaji: "resutoran",
    meaning: "restoran",
  },
  {
    kana: "ロ",
    romaji: "ro",
    exampleKana: "ロケット",
    exampleRomaji: "roketto",
    meaning: "roket",
  },
  {
    kana: "ワ",
    romaji: "wa",
    exampleKana: "ワイン",
    exampleRomaji: "wain",
    meaning: "anggur",
  },
  {
    kana: "ヲ",
    romaji: "wo",
    exampleKana: "ヲタク",
    exampleRomaji: "wotaku",
    meaning: "otaku",
  },
  {
    kana: "ン",
    romaji: "n",
    exampleKana: "ラーメン",
    exampleRomaji: "raamen",
    meaning: "ramen",
  },
];
export default KATAKANA;
